### ISSUE TITLE
GET all movies

### ISSUE THREAD

**Issue by Fabi911** [neuefische/hh-java-24-3-teamproject-team-1#1]
**As a User** 
**I need** to view a list of all my movies
**to be able to** have a comprehensive overview of my entire list.

## Description
Implement a feature that allows users to retrieve and view a list of all their movies from the backend.

## Acceptance Criteria

- [x] Create a GET "/api/movies" endpoint to fetch all movies from the backend.
- [x] Display the list of all movies on the starting page of the frontend.

## Tasks

(for developers team)

- [x] Create a Model with "Id, title and author"
- [x] Create a "View All movies" component in the UI.
- [x] Implement a GET request to retrieve all movies from the backend.
- [x] Update the frontend to display the list of movies.
- [x] Implement Unit and Integration Test.
- [x] add some styling
