### ISSUE TITLE
GET movie By Id

### ISSUE THREAD

**Issue by Fabi911** [neuefische/hh-java-24-3-teamproject-team-1#5]
**As a User** 
**I need** to search for ... in my library
**to be able to** quickly find a specific ...

#### Description
Implement a search feature that allows users to search for movie based on criteria such as title, author, or genre.

#### Acceptance Criteria

- [ ] Create a GET "/api/movies/{id}" endpoint to fetch the movie specified by the id.
- [ ] Display all informations given from the backend on a extra Route for each movie "/movies/:id
- [ ] When clicking a movie in the list view or navigating directly via the url the details page should be shown

#### Tasks

- [ ] Implement a component that shows the movie Details when you click on movie in the list view
- [ ] Create a GET request to retrieve the movie data from the backend (Get By Id).
- [ ] Implement Unit and Integration Test.
- [ ] add some styling
