### ISSUE TITLE
Edit (PUT) movie

### ISSUE THREAD

**Issue by Fabi911** [neuefische/hh-java-24-3-teamproject-team-1#6]
**As a User**
**I need** to edit the details of a movie in my library
**to be able to** update information for a book

#### Description
Implement a feature that allows users to edit the details of a movie in their library. Users should be able to modify the title, author, genre, and other information.

#### Acceptance Criteria

- [x] A "Edit"-Button is displayed on the details-page for each-movie.
- [x] When the "Edit" button for a movie is clicked, the user gets redirected to "/movies/:id/edit
- [x] On the Edit-Page an edit form for that movie should appear.
- [x] When submitting the form, then the movie information should be updated in the backend and the user should be redirected to the details page.
- [x] Create an PUT Endpoint "/api/movies/{id} to update the movie.

#### Tasks

- [x] Add an "Edit" button for each movie in the UI.
- [x] Implement an edit form to modify movie details.
- [x] Create a PUT request to update movie details on the backend.
- [x] Display updated information in the frontend after saving changes.
- [x] Implement Unit and Integration Test.
