### ISSUE TITLE
DELETE movie

### ISSUE THREAD

**Issue by Fabi911** [neuefische/hh-java-24-3-teamproject-team-1#7]
**As a User**
**I need** to delete a movie from my library
**to be able to** remove movie I no longer want in my collection.

#### Description
Implement a feature that allows users to delete a movie from their library. Users should be able to remove a book they no longer wish to keep in their collection.

#### Acceptance Criteria

- [ ] Create a DELETE Endpoint "/api/movies/{id}" which deletes the movie specified by the id.
- [ ] On the Details-Page of each movie should be a "delete" Button.
- [ ] When clicking on the "Delete" button, the movie should be removed from the database.

#### Tasks

- [ ] Add a "Delete" button for each movie in the UI.
- [ ] Create a DELETE request or endpoint to remove the movie from the backend.
- [ ] Implement Unit and Integration Test.
